# Generated by Django 4.0.10 on 2024-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_actionhistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='log',
            field=models.JSONField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='log',
            field=models.JSONField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='log',
            field=models.JSONField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='log',
            field=models.JSONField(blank=True, default='', null=True),
        ),
    ]
