# Generated by Django 4.0.10 on 2024-06-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_checkfolderbackup'),
        ('history', '0003_backuphistory_log_serverinfo_log_servicehistory_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='checkFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.checkfolderbackup'),
        ),
    ]
