# Generated by Django 4.0.10 on 2024-06-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_backuphistory_checkfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuphistory',
            name='checkFolder',
        ),
    ]
