version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./server_manager_backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_MAX_CONNECTIONS=200
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=dev_user
      - DB_PASS=dev_pass
#      - REDIS_HOST= cache
#      - REDIS_PORT= 6379
    depends_on:
      - db
#      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass

#  redis:
#    image: redis:6.0.9-alpine
#    restart: always
#    command: redis-server --save 20 1 --loglevel warning && systemctl enable redis-server && systemctl start redis-server
##    ports:
##      - '6379:6379'
#    volumes:
#      - cache:/data


volumes:
  db-data:
#  cache:
#    driver: local