# Generated by Django 4.0.10 on 2024-06-27 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderBackup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('path', models.TextField()),
                ('destination', models.TextField(blank=True, default='')),
                ('is_checking', models.BooleanField(default=False)),
                ('pattern', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
            ],
        ),
    ]
