# Generated by Django 4.0.10 on 2024-06-23 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_dbservice_backuppath'),
        ('backup', '0002_folderbackup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFolderBackup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('path', models.TextField()),
                ('pattern', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
            ],
        ),
    ]
