# Generated by Django 4.0.10 on 2024-06-23 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_checkfolderbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkfolderbackup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
