# Generated by Django 4.0.10 on 2024-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_remove_backuphistory_checkfolder'),
        ('backup', '0005_alter_checkfolderbackup_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderbackup',
            name='is_checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderbackup',
            name='pattern',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='CheckFolderBackup',
        ),
    ]
