# Generated by Django 4.0.10 on 2024-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_folderbackup_is_checking_folderbackup_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderbackup',
            name='destination',
            field=models.TextField(blank=True, default=''),
        ),
    ]
