# Generated by Django 5.0.6 on 2024-06-06 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('onSuccess', models.TextField()),
                ('onError', models.TextField()),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('actions', models.ManyToManyField(blank=True, to='server.action')),
            ],
        ),
        migrations.CreateModel(
            name='DBService',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('backup', models.BooleanField()),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.server')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='servers',
            field=models.ManyToManyField(blank=True, to='server.server'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('command', models.TextField()),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.server')),
            ],
        ),
    ]
