# Generated by Django 4.0.10 on 2024-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='dbName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='serviceName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceName',
            field=models.CharField(max_length=255),
        ),
    ]
