# Generated by Django 5.0.6 on 2024-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbservice',
            old_name='name',
            new_name='dbName',
        ),
    ]
