# Generated by Django 4.0.10 on 2024-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_name_dbservice_dbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbservice',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
