# Generated by Django 5.0.6 on 2024-06-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_dbservice_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbservice',
            old_name='name',
            new_name='serviceName',
        ),
    ]
