# Generated by Django 4.0.10 on 2024-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
