# Generated by Django 4.0.10 on 2024-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_server_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbservice',
            name='type',
            field=models.CharField(choices=[('mysql', 'MySql'), ('postgres', 'Postgres')], default='postgres', max_length=255),
        ),
    ]
