# Generated by Django 5.0.6 on 2024-06-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_name_dbservice_servicename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='serviceName',
        ),
    ]
