# Generated by Django 4.0.10 on 2024-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_dbservice_backuppath'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
