# Generated by Django 4.0.10 on 2024-06-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_action_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='onError',
        ),
        migrations.RemoveField(
            model_name='action',
            name='onSuccess',
        ),
    ]
