# Generated by Django 4.0.10 on 2024-06-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_action_onerror_remove_action_onsuccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='servers', to='server.action'),
        ),
    ]
